"""
scripts/generate_cases.py
-------------------------
Generate the test case bank: one .npz file per case, as described in
configs/test_cases.json, plus cases/README.md describing every case.

Usage (from the project root):
    python scripts/generate_cases.py                      # all cases
    python scripts/generate_cases.py --only layers3       # one case

Marmousi2 cases need the model file (data/models/marmousi2/...). The
generated .npz files do not: anyone can run the algorithms on them.
"""

import argparse
import json
import os
import sys

import numpy as np

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from src.seismic.cases import (build_velocity_profile, load_case,   # noqa: E402
                               list_cases, save_case, water_bottom_time_ms)
from src.seismic.synthetic import generate_cdp_gather                # noqa: E402


def write_readme(folder):
    """Describe every case found in the folder (always in sync with the files)."""
    lines = [
        "# Test case bank",
        "",
        "Each file is one synthetic CDP gather generated by",
        "`scripts/generate_cases.py` from `configs/test_cases.json`",
        "(1D model, hyperbolic moveout with the RMS velocity, 30 Hz Ricker",
        "wavelet, white Gaussian noise relative to each trace maximum).",
        "Load a case with `src.seismic.cases.load_case(path)`.",
        "",
        "| Case | Description | Traces | Offsets (m) | dt (ms) | Record (ms) "
        "| Noise | Water bottom (ms) | V_rms (m/s) |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for path in list_cases(folder):
        c = load_case(path)
        m = c['meta']
        lines.append(
            f"| {c['name']} | {m['description']} | {c['gather'].shape[0]} "
            f"| {c['offsets'][0]:.0f}–{c['offsets'][-1]:.0f} | {c['dt_ms']:g} "
            f"| {c['t_grid'][-1]:.0f} | {100 * m['noise_level']:.0f}% "
            f"| {m['water_bottom_ms']:.0f} "
            f"| {c['v_rms_true'].min():.0f}–{c['v_rms_true'].max():.0f} |")
    with open(os.path.join(folder, 'README.md'), 'w') as f:
        f.write("\n".join(lines) + "\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--config', default=os.path.join(ROOT, 'configs', 'test_cases.json'))
    parser.add_argument('--only', nargs='*', default=None, help='case names to generate')
    args = parser.parse_args()

    with open(args.config) as f:
        cfg = json.load(f)
    acq    = cfg['acquisition']
    folder = os.path.join(ROOT, cfg['output_dir'])
    offsets = np.linspace(acq['offset_min_m'], acq['offset_max_m'],
                          acq['n_offsets'], dtype=np.float32)

    for case in cfg['cases']:
        if args.only and case['name'] not in args.only:
            continue
        try:
            profile, spacing = build_velocity_profile(case['model'], ROOT)
        except (FileNotFoundError, OSError) as e:
            print(f"  skipped {case['name']}: model not available ({e})")
            continue

        gather, t_grid, v_rms = generate_cdp_gather(
            profile, spacing, offsets,
            dt_ms=acq['dt_ms'], t_max_ms=acq['t_max_ms'],
            f0_hz=acq['f0_hz'], noise_level=case['noise_level'],
            seed=case['seed'])

        meta = {
            'name':            case['name'],
            'description':     case['description'],
            'model':           case['model'],
            'acquisition':     acq,
            'noise_level':     case['noise_level'],
            'seed':            case['seed'],
            'water_bottom_ms': water_bottom_time_ms(profile, spacing),
        }
        path = os.path.join(folder, f"{case['name']}.npz")
        save_case(path, gather, offsets, t_grid, v_rms, acq['dt_ms'], meta)
        print(f"  {case['name']:30s} -> {os.path.relpath(path, ROOT)}  "
              f"(water bottom {meta['water_bottom_ms']:.0f} ms)")

    write_readme(folder)
    print(f"\n{len(list_cases(folder))} cases in {os.path.relpath(folder, ROOT)}/ "
          f"(description in {os.path.relpath(folder, ROOT)}/README.md)")


if __name__ == '__main__':
    main()
